pkgname=arch-init-packages
pkgver=0.1
pkgrel=0
pkgdesc='A meta-package that installs necessary software for daily usage and development.'
url='https://github.com/Davidyz/dotfiles'
arch=('any')
license=('GPL')
depends=(
    'autojump'
    'biber'
    'bluedevil'
    'cmake'
    'deno'
    'fd'
    'firefox'
    'git'
    'git-delta'
    'imagemagick'
    'lsd'
    'make'
    'nodejs'
    'npm'
    'python-pynvim'
    'ripgrep'
    'rustup'
    'starship'
    'telegram-desktop'
    'texlive'
    'texlive-binextra'
    'tree-sitter-cli'
    'typst'
    'v2ray'
    'vlc'
    'wezterm'
    'xdotool'
    'zathura'
    'zathura-pdf-mupdf'
    'zsh'
)
optdepends=(
)
conflicts=(
    'black'
)
