require('filetype.json')
require('filetype.xml')
require('filetype.yaml')

require('filetype.c_cpp')
require('filetype.java')
require('filetype.lua')
require('filetype.haskell')
require('filetype.python')
require('filetype.sh')
require('filetype.typescript')
require('filetype.vim')
require('filetype.zsh')

require('filetype.pandoc')
require('filetype.markdown')
require('filetype.html')
