vim.g.coc_global_extensions = {'coc-pyright',
  'coc-java',
  'coc-vimlsp',
  'coc-sh',
  'coc-tsserver',
  'coc-clangd',
  'coc-snippets',
  'coc-spell-checker',
  'coc-rainbow-fart',
  'coc-marketplace',
  'coc-grammarly',
  -- 'coc-json',
  'coc-ci',
  'coc-docker',
  'coc-lua',
  'coc-phpls'
}
