[symlinks]
"alacritty/alacritty.yml" = "/home/davidyz/.config/alacritty/alacritty.yml"
"chrome/chrome-flags.conf" = "/home/davidyz/.config/chrome-flags.conf"
"lsd/config.yaml" = "/home/davidyz/.config/lsd/config.yaml"
"neovim/init.lua" = "/home/davidyz/.config/nvim/init.lua"
"neovim/lua/README.md" = "/home/davidyz/.config/nvim/lua/README.md"
"neovim/lua/_utils.lua" = "/home/davidyz/.config/nvim/lua/_utils.lua"
"neovim/lua/colorscheme/main.lua" = "/home/davidyz/.config/nvim/lua/colorscheme/main.lua"
"neovim/lua/filetype/bib.lua" = "/home/davidyz/.config/nvim/lua/filetype/bib.lua"
"neovim/lua/filetype/c_cpp.lua" = "/home/davidyz/.config/nvim/lua/filetype/c_cpp.lua"
"neovim/lua/filetype/gitcommit.lua" = "/home/davidyz/.config/nvim/lua/filetype/gitcommit.lua"
"neovim/lua/filetype/haskell.lua" = "/home/davidyz/.config/nvim/lua/filetype/haskell.lua"
"neovim/lua/filetype/html.lua" = "/home/davidyz/.config/nvim/lua/filetype/html.lua"
"neovim/lua/filetype/java.lua" = "/home/davidyz/.config/nvim/lua/filetype/java.lua"
"neovim/lua/filetype/json.lua" = "/home/davidyz/.config/nvim/lua/filetype/json.lua"
"neovim/lua/filetype/lua.lua" = "/home/davidyz/.config/nvim/lua/filetype/lua.lua"
"neovim/lua/filetype/main.lua" = "/home/davidyz/.config/nvim/lua/filetype/main.lua"
"neovim/lua/filetype/markdown.lua" = "/home/davidyz/.config/nvim/lua/filetype/markdown.lua"
"neovim/lua/filetype/pandoc.lua" = "/home/davidyz/.config/nvim/lua/filetype/pandoc.lua"
"neovim/lua/filetype/php.lua" = "/home/davidyz/.config/nvim/lua/filetype/php.lua"
"neovim/lua/filetype/python.lua" = "/home/davidyz/.config/nvim/lua/filetype/python.lua"
"neovim/lua/filetype/sh.lua" = "/home/davidyz/.config/nvim/lua/filetype/sh.lua"
"neovim/lua/filetype/tex.lua" = "/home/davidyz/.config/nvim/lua/filetype/tex.lua"
"neovim/lua/filetype/typescript.lua" = "/home/davidyz/.config/nvim/lua/filetype/typescript.lua"
"neovim/lua/filetype/utils.lua" = "/home/davidyz/.config/nvim/lua/filetype/utils.lua"
"neovim/lua/filetype/vim.lua" = "/home/davidyz/.config/nvim/lua/filetype/vim.lua"
"neovim/lua/filetype/xml.lua" = "/home/davidyz/.config/nvim/lua/filetype/xml.lua"
"neovim/lua/filetype/yaml.lua" = "/home/davidyz/.config/nvim/lua/filetype/yaml.lua"
"neovim/lua/filetype/zsh.lua" = "/home/davidyz/.config/nvim/lua/filetype/zsh.lua"
"neovim/lua/keymaps/NERDCommenter.lua" = "/home/davidyz/.config/nvim/lua/keymaps/NERDCommenter.lua"
"neovim/lua/keymaps/_lsp.lua" = "/home/davidyz/.config/nvim/lua/keymaps/_lsp.lua"
"neovim/lua/keymaps/c.lua" = "/home/davidyz/.config/nvim/lua/keymaps/c.lua"
"neovim/lua/keymaps/copilot.lua" = "/home/davidyz/.config/nvim/lua/keymaps/copilot.lua"
"neovim/lua/keymaps/dap.lua" = "/home/davidyz/.config/nvim/lua/keymaps/dap.lua"
"neovim/lua/keymaps/global.lua" = "/home/davidyz/.config/nvim/lua/keymaps/global.lua"
"neovim/lua/keymaps/golden_view.lua" = "/home/davidyz/.config/nvim/lua/keymaps/golden_view.lua"
"neovim/lua/keymaps/help.lua" = "/home/davidyz/.config/nvim/lua/keymaps/help.lua"
"neovim/lua/keymaps/main.lua" = "/home/davidyz/.config/nvim/lua/keymaps/main.lua"
"neovim/lua/keymaps/markdown_preview.lua" = "/home/davidyz/.config/nvim/lua/keymaps/markdown_preview.lua"
"neovim/lua/keymaps/python.lua" = "/home/davidyz/.config/nvim/lua/keymaps/python.lua"
"neovim/lua/keymaps/shell.lua" = "/home/davidyz/.config/nvim/lua/keymaps/shell.lua"
"neovim/lua/keymaps/telescope.lua" = "/home/davidyz/.config/nvim/lua/keymaps/telescope.lua"
"neovim/lua/keymaps/utils.lua" = "/home/davidyz/.config/nvim/lua/keymaps/utils.lua"
"neovim/lua/keymaps/whichkey.lua" = "/home/davidyz/.config/nvim/lua/keymaps/whichkey.lua"
"neovim/lua/misc.lua" = "/home/davidyz/.config/nvim/lua/misc.lua"
"neovim/lua/plugins/_lazy.lua" = "/home/davidyz/.config/nvim/lua/plugins/_lazy.lua"
"neovim/lua/plugins/_lsp.lua" = "/home/davidyz/.config/nvim/lua/plugins/_lsp.lua"
"neovim/lua/plugins/_lualine.lua" = "/home/davidyz/.config/nvim/lua/plugins/_lualine.lua"
"neovim/lua/plugins/alpha.lua" = "/home/davidyz/.config/nvim/lua/plugins/alpha.lua"
"neovim/lua/plugins/copilot.lua" = "/home/davidyz/.config/nvim/lua/plugins/copilot.lua"
"neovim/lua/plugins/dap.lua" = "/home/davidyz/.config/nvim/lua/plugins/dap.lua"
"neovim/lua/plugins/fauxpilot.lua" = "/home/davidyz/.config/nvim/lua/plugins/fauxpilot.lua"
"neovim/lua/plugins/golden_view.lua" = "/home/davidyz/.config/nvim/lua/plugins/golden_view.lua"
"neovim/lua/plugins/haskell.lua" = "/home/davidyz/.config/nvim/lua/plugins/haskell.lua"
"neovim/lua/plugins/jupytext.lua" = "/home/davidyz/.config/nvim/lua/plugins/jupytext.lua"
"neovim/lua/plugins/markdown_preview.lua" = "/home/davidyz/.config/nvim/lua/plugins/markdown_preview.lua"
"neovim/lua/plugins/mason_tools.lua" = "/home/davidyz/.config/nvim/lua/plugins/mason_tools.lua"
"neovim/lua/plugins/null_ls.lua" = "/home/davidyz/.config/nvim/lua/plugins/null_ls.lua"
"neovim/lua/plugins/nvim_autopairs.lua" = "/home/davidyz/.config/nvim/lua/plugins/nvim_autopairs.lua"
"neovim/lua/plugins/pandoc.lua" = "/home/davidyz/.config/nvim/lua/plugins/pandoc.lua"
"neovim/lua/plugins/tree_sitter.lua" = "/home/davidyz/.config/nvim/lua/plugins/tree_sitter.lua"
"neovim/lua/plugins/treesitter-context.lua" = "/home/davidyz/.config/nvim/lua/plugins/treesitter-context.lua"
"neovim/lua/plugins/utils.lua" = "/home/davidyz/.config/nvim/lua/plugins/utils.lua"
"wezterm/onedarkpro.toml" = "/home/davidyz/.config/wezterm/onedarkpro.toml"
"wezterm/wezterm.lua" = "/home/davidyz/.config/wezterm/wezterm.lua"
"zsh/.p10k.zsh" = "/home/davidyz/.p10k.zsh"
"zsh/.zshrc" = "/home/davidyz/.zshrc"

[templates]
