[neovim.files]
"neovim/" = { target = "~/.config/nvim/", type = "symbolic" }

[hyprland.files]
"hyprland/" = "~/.config/hypr/"

[zsh.files]
"zsh/" = "~/"

[alacritty.files]
"alacritty/" = "~/.config/alacritty/"

[chrome.files]
"chrome/chrome-flags.conf" = "~/.config/chrome-flags.conf"

[lsd.files]
"lsd/config.yaml" = "~/.config/lsd/config.yaml"

[wezterm.files]
"wezterm/" = "~/.config/wezterm/"

[ahk.files]
"autohotkeys/" = "~/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Startup/"

[presenterm.files]
"presenterm/" = "~/.config/presenterm/"

[ranger.files]
"ranger/" = "~/.config/ranger/"

[starship.files]
"starship/starship.toml" = "~/.config/starship.toml"

[delta.files]
"delta/" = "~/.config/delta/"

[bat.files]
"bat/" = "~/.config/bat/"

[glow.files]
"glow/glow.yml" = { target = "~/.config/glow/glow.yml", type = "template" }
"glow/catppuccin-mocha.json" = { target = "~/.config/glow/catppuccin-mocha.json", type = "symbolic" }
