[neovim.files]
# "neovim/init.lua" = "~/.config/nvim/init.lua"
"neovim/" = "~/.config/nvim/"

[zsh.files]
"zsh/.zshrc" = "~/.zshrc"
"zsh/.p10k.zsh" = "~/.p10k.zsh"

[alacritty.files]
"alacritty/alacritty.yml" = "~/.config/alacritty/alacritty.yml"

[chrome.files]
"chrome/chrome-flags.conf" = "~/.config/chrome-flags.conf"

[lsd.files]
"lsd/config.yaml" = "~/.config/lsd/config.yaml"

[wezterm.files]
"wezterm/wezterm.lua" = "~/.config/wezterm/wezterm.lua"
"wezterm/onedarkpro.toml" = "~/.config/wezterm/onedarkpro.toml"

[ahk.files]
"autohotkeys/app_runner.ahk" = "~/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Startup/app_runner.ahk"
"autohotkeys/tiling.ahk" = "~/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Startup/tiling.ahk"

[presenterm.files]
"presenterm/config.yaml" = "~/.config/presenterm/config.yaml"
"presenterm/themes" = "~/.config/presenterm/themes/"

[ranger.files]
"ranger/" = "~/.config/ranger/"
